# This is the configuration for your PRODUCTION environment.
# It is used by `make prod-vbd`.
version = 0.1

[default.deploy.parameters]
stack_name = "home-app"
region = "us-east-1"
profile = "fas"
resolve_s3 = true
s3_prefix = "home-app"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
disable_rollback = false
image_repositories = []

# --- Parameters ---
# All parameters are now defined as explicit keys.
# The old "parameter_overrides" string is removed.
EnvironmentName = "prod"
UsersTableName = "e11-users"
OidcSecretId = "arn:aws:secretsmanager:us-east-1:586794483136:secret:harvardkey-oidc-JGPzjb"
SshSecretId = "arn:aws:secretsmanager:us-east-1:586794483136:secret:ssh-keys-EqRSxl"
HostedZoneId = "Z05034072HOMXYCK23BRA"
CertificateArn = ""
LogLevel = "DEBUG"
