# This is the configuration for your STAGING environment.
# It is used by `make stage-vbd`.
version = 0.1

[default.build.parameters]
# SAM build reads from this section
EnvironmentName = "stage"
UsersTableName = "e11-users"
OidcSecretId = "arn:aws:secretsmanager:us-east-1:586794483136:secret:harvardkey-oidc-JGPzjb"
SshSecretId = "arn:aws:secretsmanager:us-east-1:586794483136:secret:ssh-keys-EqRSxl"
SqsSecretId = "arn:aws:secretsmanager:us-east-1:586794483136:secret:sqs-auth-secret-CkrRul"
HostedZoneId = "Z05034072HOMXYCK23BRA"
CertificateArn = ""
LogLevel = "DEBUG"

[default.deploy.parameters]
# SAM deploy reads from this section
stack_name = "home-app-stage"
profile = "fas"
resolve_s3 = true
s3_prefix = "home-app-stage"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
disable_rollback = false
image_repositories = []
# --- Parameters ---
EnvironmentName = "stage"
UsersTableName = "e11-users"
OidcSecretId = "arn:aws:secretsmanager:us-east-1:586794483136:secret:harvardkey-oidc-JGPzjb"
SshSecretId = "arn:aws:secretsmanager:us-east-1:586794483136:secret:ssh-keys-EqRSxl"
SqsSecretId = "arn:aws:secretsmanager:us-east-1:586794483136:secret:sqs-auth-secret-CkrRul"
HostedZoneId = "Z05034072HOMXYCK23BRA"
CertificateArn = ""
LogLevel = "DEBUG"
parameter_overrides = "EnvironmentName=\"stage\" UsersTableName=\"e11-users\" LeaderboardTableName=\"Leaderboard\" HostedZoneId=\"Z05034072HOMXYCK23BRA\" CertificateArn=\"\" OidcSecretId=\"arn:aws:secretsmanager:us-east-1:586794483136:secret:harvardkey-oidc-JGPzjb\" SshSecretId=\"arn:aws:secretsmanager:us-east-1:586794483136:secret:ssh-keys-EqRSxl\" SqsSecretId=\"arn:aws:secretsmanager:us-east-1:586794483136:secret:sqs-auth-secret-CkrRul\" LogLevel=\"INFO\""

[default.global.parameters]
region = "us-east-1"
