name: CI for e11-cli

on:
  push:
    branches:
      - main
      - dev
  pull_request:

# Cancel in-progress runs when a new run is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: etc/e11-cli
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]
    env:
      AWS_DEFAULT_REGION: 'localhost'
      AWS_ENDPOINT_URL: 'http://localhost:8000'
      AWS_ACCESS_KEY_ID: 'minioadmin'
      AWS_SECRET_ACCESS_KEY: 'minioadmin'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pipx, Poetry, and Java
        run: |
          sudo apt -y update
          sudo apt -y install python3-venv pipx openjdk-17-jre-headless
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          pipx install poetry
          poetry --version
          java -version

      - name: e11 command tests with coverage
        run: |
          make lint
          make check

      - name: lambda-home tests with coverage require Python 3.13
        if: matrix.python-version == '3.13'
        run: |
          (cd lambda-home; make install)
          (cd lambda-home; make lint)
          (cd lambda-home; make check)

      - name: lambda-leaderboard tests with coverage require Python 3.13
        if: matrix.python-version == '3.13'
        run: |
          (cd lambda-leaderboard; make install)
          (cd lambda-leaderboard; make check)

      - name: list coverage files
        run: |
          find . -name coverage.xml -ls

      - name: Upload coverage to Codecov
        if: matrix.python-version == '3.13'
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml,lambda-home/coverage.xml,lambda-leaderboard/coverage.xml
          flags: unittests
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: matrix.python-version == '3.13'
        uses: codecov/test-results-action@v1
        with:
          files: junit1.xml,lambda-home/junit1.xml
          token: ${{ secrets.CODECOV_TOKEN }}
